SET SERVEROUTPUT ON;

DECLARE
    CURSOR CUR_FOR_LOOP_EMP IS
    SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEE WHERE EMPID <= 5;
BEGIN
    FOR L_INDX IN CUR_FOR_LOOP_EMP
    LOOP
        DBMS_OUTPUT.PUT_LINE(L_INDX.FIRST_NAME ||' '|| L_INDX.LAST_NAME ||' '|| L_INDX.SALARY);
    END LOOP;
END;
/
