--------------------WEAK REF CURSOR----------------------------------------------------
SET SERVEROUTPUT ON;

DECLARE
    TYPE WK_REF_CUR IS REF CURSOR;
    CUR_VAR WK_REF_CUR;
    
    FNAME EMPLOYEE.FIRST_NAME%TYPE;
    SAL EMPLOYEE.salary%TYPE;
    
BEGIN
    OPEN CUR_VAR FOR SELECT FIRST_NAME, SALARY FROM EMPLOYEE WHERE EMPID = 1;
    FETCH CUR_VAR INTO FNAME, SAL;
    CLOSE CUR_VAR;
    DBMS_OUTPUT.PUT_LINE(FNAME || ' ' || SAL);
END;
/

----------------------------------------------------------------------------------------
SET SERVEROUTPUT ON;

DECLARE
    TYPE WK_REF_CURSOR IS REF CURSOR;
    CUR_VAR WK_REF_CURSOR;
    
    F_NAME EMPLOYEE.first_name%TYPE;
    L_NAME EMPLOYEE.last_name%TYPE;
    HIREDATE EMPLOYEE.hire_date%TYPE;
    EXP NUMBER;
    
BEGIN
    OPEN CUR_VAR FOR SELECT FIRST_NAME, LAST_NAME, HIRE_DATE, TRUNC(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)/12) AS EXP FROM EMPLOYEE;
    LOOP
        FETCH CUR_VAR INTO F_NAME, L_NAME, HIREDATE, EXP;
        EXIT WHEN CUR_VAR%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(F_NAME || ' ' || L_NAME || ' JOINED ON ' || HIREDATE || ' AND HAVING ' || EXP || ' YEARS OF EXPERIENCE.');
    END LOOP;
    CLOSE CUR_VAR;
END;
/
