CREATE TABLE DB_EVENT_AUDIT
(
    EVENT_TYPE VARCHAR2(30),
    LOGON_DATE DATE,
    LOGON_TIME VARCHAR2(30),
    LOGOFF_DATE DATE,
    LOGOFF_TIME VARCHAR2(30)
);

select * from db_event_audit;

SET SERVEROUTPUT ON;

CREATE OR REPLACE TRIGGER TR_DB_LOGON_AUDIT
AFTER LOGON ON SCHEMA
BEGIN
    INSERT INTO DB_EVENT_AUDIT VALUES(
        ORA_SYSEVENT,
        SYSDATE,
        TO_CHAR(SYSDATE,'hh24:mi:ss'),
        NULL,
        NULL);
    COMMIT;
END;
/

DISC;

conn amitpl/amitpl9;
