----------------------------PARAMETERIZED CURSOR---------------------------------------
SET SERVEROUTPUT ON;

ACCEPT VAR_NUM NUMBER PROMPT 'Enter Employee ID';
DECLARE
    V_FNAME VARCHAR2(10);
    V_LNAME VARCHAR2(10);
    CURSOR CUR_EMP(VAR_NUM NUMBER) IS
    SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEE WHERE EMPID = VAR_NUM;
BEGIN
    OPEN CUR_EMP(&VAR_NUM);
    LOOP
        FETCH CUR_EMP INTO V_FNAME, V_LNAME;
        EXIT WHEN CUR_EMP%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(V_FNAME || ' ' || V_LNAME);
    END LOOP;
END;
/

----------------------------------------------------------------------------------------
SET SERVEROUTPUT ON;

ACCEPT VAR_NUM NUMBER PROMPT 'Enter Employee ID';
DECLARE
    V_FNAME VARCHAR2(10);
    V_LNAME VARCHAR2(10);
    CURSOR CUR_EMP(VAR_NUM NUMBER) IS
    SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEE WHERE EMPID <= VAR_NUM;
BEGIN
    OPEN CUR_EMP(&VAR_NUM);
    LOOP
        FETCH CUR_EMP INTO V_FNAME, V_LNAME;
        EXIT WHEN CUR_EMP%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(V_FNAME || ' ' || V_LNAME);
    END LOOP;
END;
/
