SET SERVEROUTPUT ON;

DECLARE
    CURSOR P_CUR_FOR_EMP(VAR_EMPID NUMBER) IS
    SELECT EMPID, FIRST_NAME FROM EMPLOYEE WHERE EMPID = VAR_EMPID;
BEGIN
    FOR L_INDX IN P_CUR_FOR_EMP(2) 
    LOOP
        DBMS_OUTPUT.PUT_LINE(L_INDX.EMPID || ' ' || L_INDX.FIRST_NAME);
    END LOOP;
END;
/
