---------------------EXECUTE IMMEDIATE USING BULK COLLECT INTO CLAUSE-------------------------

SET SERVEROUTPUT ON;

DECLARE
    TYPE NT_TABLE IS TABLE OF VARCHAR2(20);
    FNAME NT_TABLE;
    SQL_QRY VARCHAR2(100);
BEGIN
    SQL_QRY := 'SELECT FIRST_NAME FROM EMPLOYEE';
    EXECUTE IMMEDIATE SQL_QRY BULK COLLECT INTO FNAME;
    FOR IDX IN 1..FNAME.COUNT
    LOOP
        DBMS_OUTPUT.PUT_LINE(IDX || ' - ' || FNAME(IDX));
    END LOOP;
END;
/
