---------------------------NESTED TABLE COLLECTION - DELETE PROCEDURE------------------------------------------------------

SET SERVEROUTPUT ON;

DECLARE
    TYPE MY_NESTED_TABLE IS TABLE OF NUMBER;
    VAR_NUM MY_NESTED_TABLE := MY_NESTED_TABLE(1,2,3,4,5,6,7,8,9,10);
BEGIN
    DBMS_OUTPUT.PUT_LINE('THE VALUES AT INDEX[5] IS ' || VAR_NUM(5));
    VAR_NUM.DELETE(5);
    IF VAR_NUM.EXISTS(5) THEN
        DBMS_OUTPUT.PUT_LINE('VALUE AT INDEX[5] AFTER DELETE IS ' || VAR_NUM(5));
    ELSE
        DBMS_OUTPUT.PUT_LINE('THE RECORD HAS BEEN DELETED');
    END IF;
END;
/
