------------------Parameterized PROCEDURE------------------------------------------------------

SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE PR_EMP (NUM NUMBER)
IS
V_EMP EMPLOYEE%ROWTYPE;
BEGIN
    SELECT * INTO V_EMP FROM EMPLOYEE WHERE EMPID = NUM;
    DBMS_OUTPUT.PUT_LINE(V_EMP.EMPID|| ' ' ||V_EMP.FIRST_NAME ||' ' || V_EMP.LAST_NAME || ' ' || V_EMP.HIRE_DATE || ' ' || V_EMP.SALARY);
END PR_EMP;
/

EXEC PR_EMP(2);


SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE PR_EMP_SAL(EID NUMBER, SAL NUMBER)
IS
BEGIN
    UPDATE EMPLOYEE SET SALARY = SALARY * SAL WHERE EMPID = EID;
    DBMS_OUTPUT.PUT_LINE('SALARY UPDATED SUCCESSFULLY.');
END PR_EMP_SAL;
/

EXEC PR_EMP_SAL(1,2);
