SET SERVEROUTPUT ON;

CREATE OR REPLACE TRIGGER TR_BU_UPDATE_DEPT
INSTEAD OF UPDATE ON VW_DARKCAMPER1
FOR EACH ROW
BEGIN
    UPDATE DEPT SET DNAME = :NEW.dname WHERE DNAME = :OLD.dname;
    UPDATE LOC SET NAME = :NEW.name WHERE NAME = :OLD.name;
END;
/

update vw_darkcamper1 set dname = 'Mechanical' WHERE name = 'Pune';
