--------------- NESTED TABLE COLLECTION - EXISTS METHOD----------------------------

SET SERVEROUTPUT ON;

DECLARE 
    TYPE MY_NESTED_TABLE IS TABLE OF VARCHAR2(20);
    COL_VAR MY_NESTED_TABLE := MY_NESTED_TABLE('SUPERMAN','BATMAN','IRONMAN');
BEGIN
    IF COL_VAR.EXISTS(1) THEN
        DBMS_OUTPUT.PUT_LINE('HEY, WE FOUND ' ||COL_VAR(1));
    END IF;
END;
/



-------------------------------------------------------------------------------------
SET SERVEROUTPUT ON;

DECLARE 
    TYPE MY_NESTED_TABLE IS TABLE OF VARCHAR2(20);
    COL_VAR MY_NESTED_TABLE := MY_NESTED_TABLE('SUPERMAN','BATMAN','IRONMAN');
BEGIN
    IF COL_VAR.EXISTS(4) THEN
        DBMS_OUTPUT.PUT_LINE('HEY, WE FOUND ' ||COL_VAR(1));
    ELSE
        DBMS_OUTPUT.PUT_LINE('THIS INDEX IS EMPTY, SO WE ARE INSERTING NEW RECORD HERE.');
        COL_VAR.EXTEND;
        COL_VAR(4) :='SPIDERMAN';
    END IF;
        DBMS_OUTPUT.PUT_LINE('WE HAVE ENTERED NEW RECORD AT THIS INDEX AND THAT IS  : ' || COL_VAR(4));
END;
/
