----------------------------EXECUTE IMMEDIATE USING BIND VARIABLE (UPDATE)----------------------------

SET SERVEROUTPUT ON;

DECLARE
    SQL_SMT VARCHAR2(150);
BEGIN
    SQL_SMT := 'UPDATE STUD_INFO SET STUDENT_NAME = :NEW_NAME WHERE STUDENT_NAME = :OLD_NAME';
    
    EXECUTE IMMEDIATE SQL_SMT USING 'SUMITRA', 'SUMITA';
END;
/

SELECT * FROM STUD_INFO;


SELECT * FROM EMPLOYEE;

-----------------------------------------------------------------------------------------------------
SET SERVEROUTPUT ON;

DECLARE
    SQL_QRY VARCHAR2(300);
BEGIN
    SQL_QRY := 'UPDATE EMPLOYEE SET SALARY = :NEW_SAL WHERE EMPID = :OLD_EMPID';
    EXECUTE IMMEDIATE SQL_QRY USING '36500', '1';
END;
/
