-----------------EXECUTE IMMEDIATE USING BIND VARIABLE (INSERT)----------------------------

CREATE TABLE STUD_INFO(
            STUDENT_NAME VARCHAR2(10)
            );

SET SERVEROUTPUT ON;

DECLARE
    SQL_SMT VARCHAR2(100);
BEGIN
    SQL_SMT := 'INSERT INTO STUD_INFO(STUDENT_NAME)VALUES(:STUD_NAME)';
    
    EXECUTE IMMEDIATE SQL_SMT USING 'AMIT';
END;
/

SELECT * FROM STUD_INFO;

----------------------------------------------------------------------------------------
SET SERVEROUTPUT ON;

DECLARE
    SQL_SMT VARCHAR2(200);
BEGIN
    SQL_SMT := 'INSERT INTO EMPLOYEE VALUES(:NEW_EMPID, :NEW_FNAME, :NEW_LNAME, :NEW_HIREDATE, :NEW_SALARY)';
    
    EXECUTE IMMEDIATE SQL_SMT USING '6' , 'SHRIMAN' , 'JOSHI' , '27-JAN-2014' , '25000';
END;
/

SELECT * FROM EMPLOYEE;
