------------------CURSOR - STRONG REF CURSOR-----------------------------------------

SET SERVEROUTPUT ON;

DECLARE
    TYPE CUR_EMP IS REF CURSOR RETURN employee%ROWTYPE;
    CUR_VAR CUR_EMP;
    MY_EMP EMPLOYEE%ROWTYPE;
BEGIN
    OPEN CUR_VAR FOR SELECT * FROM EMPLOYEE WHERE EMPID < 3;
    FOR I IN 1..3 LOOP
        FETCH CUR_VAR INTO MY_EMP;
    END LOOP;
    CLOSE CUR_VAR;
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME IS ' || MY_EMP.FIRST_NAME || ' ' || MY_EMP.LAST_NAME || '. AND HAS SALARY ' || MY_EMP.SALARY);
END;
/

--------------------------------------------------------------------------------------------------
SET SERVEROUTPUT ON;

DECLARE
    TYPE REF_CUR IS REF CURSOR RETURN SPORTS_CARS%ROWTYPE;
    CUR_VAR REF_CUR;
    RESULT_VAR SPORTS_CARS%ROWTYPE;
    
BEGIN
    OPEN CUR_VAR FOR SELECT * FROM SPORTS_CARS WHERE CAR_ID = 12;
    FETCH CUR_VAR INTO RESULT_VAR;
    CLOSE CUR_VAR;
    DBMS_OUTPUT.PUT_LINE(RESULT_VAR.CAR_NAME || ' ' || RESULT_VAR.BRAND_NAME);
END;
/

---------------------------------------------------------------------------------------------------
SET SERVEROUTPUT ON;

DECLARE
    TYPE REF_CUR IS REF CURSOR RETURN SPORTS_CARS%ROWTYPE;
    CUR_VAR REF_CUR;
    RESULT_VAR SPORTS_CARS%ROWTYPE;
    
BEGIN
    OPEN CUR_VAR FOR SELECT * FROM SPORTS_CARS WHERE CAR_ID <= 12;
    FOR I IN 1..12 LOOP
    FETCH CUR_VAR INTO RESULT_VAR;
    DBMS_OUTPUT.PUT_LINE(RESULT_VAR.CAR_NAME || ' ' || RESULT_VAR.BRAND_NAME);
    END LOOP;
    CLOSE CUR_VAR;
    
END;
/
