---------------FORALL STATEMENT - INDICES OF---------------------------------

SET SERVEROUTPUT ON;

CREATE TABLE TUTORIAL_INDICESOF(
                MULTI NUMBER
                );

DECLARE
    TYPE NT_TBL IS TABLE OF NUMBER;
    RES_VAR NT_TBL := NT_TBL (9,18,27,36,45,54,63,72,81,90);
    TOT_REC NUMBER;
    
BEGIN
    RES_VAR.DELETE(3,6);
    FORALL IDX IN INDICES OF RES_VAR
        INSERT INTO tutorial_INDICESOF VALUES(RES_VAR(IDX));
    
    SELECT COUNT(*) INTO TOT_REC FROM tutorial_INDICESOF;
    DBMS_OUTPUT.PUT_LINE('TOTAL NUMBER OF RECORDS INSERTED IS  ' ||TOT_REC);
END;
/

SELECT * FROM tutorial_indicesof;

------------------------------------------------------------------------------------------
SET SERVEROUTPUT ON;

DECLARE
    TYPE MY_NESTED_TABLE IS TABLE OF NUMBER;
    VAR_RESULT MY_NESTED_TABLE := MY_NESTED_TABLE(1,2,3,4,5,6,7,8,9,10);
    TOT_REC NUMBER;
BEGIN
    VAR_RESULT.DELETE(5,9);
    FORALL IDX IN INDICES OF VAR_RESULT
        INSERT INTO TUTORIAL_INDICESOF VALUES(VAR_RESULT(IDX));
    
    SELECT COUNT(*) INTO TOT_REC FROM TUTORIAL_INDICESOF;
    DBMS_OUTPUT.PUT_LINE('TOTAL NUMBER OF RECORDS INSERTED ARE  : ' || TOT_REC);
END;
/

SELECT * FROM tutorial_indicesof;
