------------------------------PACKAGES IN PLSQL---------------------------------

CREATE OR REPLACE PACKAGE pkg_darkcamper IS
    FUNCTION PRNT_STRNG RETURN VARCHAR2;
    PROCEDURE PROC_SUPERHERO (F_NAME VARCHAR2, L_NAME VARCHAR2);
END PKG_DARKCAMPER;

CREATE OR REPLACE PACKAGE BODY pkg_darkcamper IS
    FUNCTION PRNT_STRNG RETURN VARCHAR2 IS
        BEGIN
            RETURN 'AMTSWRLD.COM';
        END PRNT_STRNG;
    
    PROCEDURE PROC_SUPERHERO(F_NAME VARCHAR2, L_NAME VARCHAR2) IS
        BEGIN
            INSERT INTO NEW_SUPERHEROES VALUES(F_NAME, L_NAME);
        END PROC_SUPERHERO;
END pkg_darkcamper;
/

CREATE TABLE NEW_SUPERHEROES(F_NAME VARCHAR2(20), L_NAME VARCHAR2(20));

SET SERVEROUTPUT ON;
BEGIN
    DBMS_OUTPUT.PUT_LINE(PKG_DARKCAMPER.PRNT_STRNG);
END;

BEGIN
    PKG_DARKCAMPER.PROC_SUPERHERO('Black','Panther');
END;

SELECT * FROM NEW_SUPERHEROES;

---------------------------------------------------------------------------------------

SET SERVEROUTPUT ON;

CREATE OR REPLACE PACKAGE PKG_DARKCAMPER1 IS
    FUNCTION DISP_MSG RETURN VARCHAR2;
    PROCEDURE PROC_SP_HEROES(F_NAME VARCHAR2, L_NAME VARCHAR2);
END PKG_DARKCAMPER1;

CREATE OR REPLACE PACKAGE BODY PKG_DARKCAMPER1 IS
    FUNCTION DISP_MSG RETURN VARCHAR2 IS
        BEGIN
            RETURN 'Whats up Internet?';
    END DISP_MSG;
    
    PROCEDURE PROC_SP_HEROES(F_NAME VARCHAR2, L_NAME VARCHAR2) IS
        BEGIN
            INSERT INTO NEW_SUPERHEROES VALUES(F_NAME, L_NAME);
    END PROC_SP_HEROES;
END PKG_DARKCAMPER1;
/

BEGIN 
    DBMS_OUTPUT.PUT_LINE(PKG_DARKCAMPER1.DISP_MSG);
END;

BEGIN
    PKG_DARKCAMPER1.PROC_SP_HEROES('Dark','Camper');
END;

select * from new_superheroes;
