-----------------------BULK COLLECT CLAUSE - SELECT INTO -------------------------

SET SERVEROUTPUT ON;

DECLARE
    TYPE BC_FNAME IS TABLE OF VARCHAR2(20);
    FNAME BC_FNAME;
BEGIN
    SELECT FIRST_NAME BULK COLLECT INTO FNAME FROM EMPLOYEE;
    FOR IDX IN 1..FNAME.COUNT 
    LOOP
        DBMS_OUTPUT.PUT_LINE(IDX || ' - ' || FNAME(IDX));
    END LOOP;
END;
/
