-------------------FORALL STATEMENT - LOWER AND UPPER BOUND-------------------

SET SERVEROUTPUT ON;

CREATE TABLE TUTORIAL(
                MULLTI NUMBER(5)
                );
DECLARE
    TYPE MY_ARRAY IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
    COL_VAR MY_ARRAY;
    TOT_REC NUMBER;
BEGIN
    FOR I IN 1..10 LOOP
        COL_VAR(I) := 9 * I;
    END LOOP;
    
    FORALL IDX IN 1..10
        INSERT INTO TUTORIAL(MULLTI) VALUES(COL_VAR(IDX));
END;
/

SELECT * FROM TUTORIAL;
