--------------------FORALL STATEMENT - VALUES OF BOUND CLAUSE--------------------------

SET SERVEROUTPUT ON;

DECLARE 
    TYPE MY_NESTED_TABLE IS TABLE OF NUMBER;
    SOURCE_COL MY_NESTED_TABLE := MY_NESTED_TABLE (10,20,30,40,50,60,70,80,90,100);
    
    TYPE MY_ARRAY IS TABLE OF PLS_INTEGER INDEX BY PLS_INTEGER;
    INDEX_COL MY_ARRAY;
    
BEGIN
    INDEX_COL(1) := 3;
    INDEX_COL(7) := 7;
    INDEX_COL(12) := 8;
    INDEX_COL(28) := 10;
    
    FORALL IDX IN VALUES OF INDEX_COL
        INSERT INTO TUTORIAL_VALUESOF VALUES(SOURCE_COL(IDX));
END;
/

SELECT * FROM tutorial_valuesof;

-------------------------------------------------------------------------------------------
SET SERVEROUTPUT ON;

DECLARE
    TYPE MY_NESTED_TABLE IS TABLE OF NUMBER;
    SOURCE_COL MY_NESTED_TABLE := MY_NESTED_TABLE (1,2,3,4,5,6,7,8,9,10);
    
    TYPE MY_ARRAY IS TABLE OF PLS_INTEGER INDEX BY PLS_INTEGER;
    INDEX_COL MY_ARRAY;
BEGIN
    INDEX_COL(1) := 3;
    INDEX_COL(3) := 7;
    INDEX_COL(5) := 8;
    INDEX_COL(7) := 9;
    
    FORALL IDX IN VALUES OF INDEX_COL
        INSERT INTO TUTORIAL_VALUESOF VALUES(SOURCE_COL(IDX));
END;
/

SELECT * FROM TUTORIAL_VALUESOF;
