------------------------NESTED TABLE COLLECTION - LIMIT()-------------------------
SET SERVEROUTPUT ON;

DECLARE
    TYPE MY_VARRAY IS VARRAY(5) OF NUMBER;
    V_VARRAY MY_VARRAY := MY_VARRAY();
BEGIN
    DBMS_OUTPUT.PUT_LINE('TOTAL INDEXES '|| V_VARRAY.LIMIT);
    DBMS_OUTPUT.PUT_LINE('RESULT OF COUNT FUNCTION ' || V_VARRAY.COUNT);
END;
/
O/P : TOTAL INDEXES 5
RESULT OF COUNT FUNCTION 0

----------------------------------------------------------------------------------
SET SERVEROUTPUT ON;

DECLARE
    TYPE MY_VARRAY IS VARRAY(5) OF NUMBER;
    V_VARRAY MY_VARRAY := MY_VARRAY(1,2);
BEGIN
    DBMS_OUTPUT.PUT_LINE('TOTAL INDEXES '|| V_VARRAY.LIMIT);
    
    DBMS_OUTPUT.PUT_LINE('RESULT OF COUNT FUNCTION ' || V_VARRAY.COUNT);
END;
/

O/P: TOTAL INDEXES 5
RESULT OF COUNT FUNCTION 2
