CREATE TABLE EMPLOYEE(
    EMPID NUMBER,
    FIRST_NAME VARCHAR2(20),
    LAST_NAME VARCHAR2(20),
    HIRE_DATE DATE,
    SALARY NUMBER);
    
INSERT INTO EMPLOYEE VALUES(5, 'Sumitra', 'Adhav','27-JAN-2014',22000);

SELECT * FROM EMPLOYEE;



SET SERVEROUTPUT ON;

DECLARE
    v_name VARCHAR2(20);
    CURSOR CUR_EMP_NAME IS SELECT FIRST_NAME FROM EMPLOYEE WHERE EMPID < 3;
BEGIN
    OPEN CUR_EMP_NAME;
    LOOP
        FETCH CUR_EMP_NAME INTO v_name;
        DBMS_OUTPUT.PUT_LINE(v_name);
        EXIT WHEN CUR_EMP_NAME%NOTFOUND;
    END LOOP;
    CLOSE CUR_EMP_NAME;
END;
/
